#!/usr/bin/env python3

def frequentWords(inputString, length):
  maxCount = 0
  wordHistogram = {}
  inputLength = len(inputString)
  for i in range(inputLength - length):
    chunk = inputString[i:i+length]
    if chunk in wordHistogram:
      wordHistogram[chunk] += 1
    else:
      wordHistogram[chunk] = 1
    if wordHistogram[chunk] > maxCount:
      maxCount = wordHistogram[chunk]
  return [key for key in wordHistogram.keys() if wordHistogram[key] == maxCount]
  

def main():
  inputString = "CGACACTGTGGAGTTAGGGAGTTAGAGCCGTCGAACGACACTGTCGACACTGTGCCATTACCGAGCCGTCGAACGACACTGTGCCATTACCGCTGCATATGCCATTACCGCTGCATATCTGCATATCTGCATATCGACACTGTCTGCATATAGCCGTCGAACGACACTGTCGACACTGTGGAGTTAGGCCATTACCGCGACACTGTAGCCGTCGAACGACACTGTCTGCATATCGACACTGTAGCCGTCGAAGGAGTTAGGGAGTTAGGCCATTACCGAGCCGTCGAAGCCATTACCGCGACACTGTAGCCGTCGAAGGAGTTAGGGAGTTAGGCCATTACCGGGAGTTAGAGCCGTCGAAGCCATTACCGCTGCATATGGAGTTAGCGACACTGTAGCCGTCGAACGACACTGTAGCCGTCGAACGACACTGTCGACACTGTCTGCATATAGCCGTCGAAAGCCGTCGAAGGAGTTAGAGCCGTCGAACTGCATATAGCCGTCGAACTGCATATGCCATTACCGAGCCGTCGAACGACACTGTGGAGTTAGGGAGTTAGGCCATTACCGCTGCATATGGAGTTAGCTGCATATCGACACTGTAGCCGTCGAAGGAGTTAGGCCATTACCGAGCCGTCGAAGGAGTTAGAGCCGTCGAAAGCCGTCGAAAGCCGTCGAAGCCATTACCGCTGCATATCGACACTGTCTGCATATGGAGTTAGGGAGTTAGGCCATTACCGGCCATTACCGCGACACTGTCGACACTGTCGACACTGTGGAGTTAGAGCCGTCGAACGACACTGTCGACACTGTGCCATTACCGCGACACTGTCGACACTGTGGAGTTAGAGCCGTCGAAAGCCGTCGAACTGCATATAGCCGTCGAAGCCATTACCGCTGCATATGGAGTTAGGCCATTACCG"
  inputCount = 14
  words = frequentWords(inputString, inputCount)
  for word in words:
    print(word, end=" ")
  print()

if __name__ == '__main__':
  main()